openapi: 3.0.1
info:
  title: service-name
  description: basic template for map colonies service
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8080
paths:
  /status:
    get:
      operationId: getStatus
      tags:
        - Status
      summary: gets the agent status
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/status'
    post:
      operationId: updateStatus
      tags:
        - Status
      summary: updates the agent status
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/status'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/status'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    status:
      type: object
      required:
        - isWatching
      properties:
        isWatching:
          type: boolean
