{{- $chartName := include "discrete-agent-db.name" . -}}
{{- $tracingUrl := include "discrete-agent-db.tracingUrl" . -}}
{{- $metricsUrl := include "discrete-agent-db.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  OPENAPI_FILE_PATH: {{ .Values.env.openApiFilPath | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  SERVER_PORT: {{ .Values.env.port | quote }}
  DB_HOST: {{ .Values.rasterCommon.db.host | quote }}
  DB_PORT: {{ .Values.rasterCommon.db.port | quote}}
  DB_NAME: {{ .Values.rasterCommon.db.name | quote }}
  DB_SCHEMA: {{ .Values.env.db.schema | quote }}
  DB_LOGGING: {{ .Values.env.db.logging | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
{{- end }}
